PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?d {
{
    ?d rdfs:subClassOf* obo:DUO_0000001.
}
UNION
{
    ?d rdfs:subClassOf* obo:DUO_0000017.
}
}