/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class OntoFoxInputParser {

    //[URI of the OWL(RDF/XML) output file]
    private String uri = null;
    //[Source ontology]
    private String sourceOntology = null;
    //[Low level source term URIs]
    private Set<IRI> lowIRI = null;
    //[Top level source term URIs and target direct superclass URIs]
    //[Source term retrieval setting]
    //[Branch extractions from source term URIs and target direct superclass URIs]
    //[Source annotation URIs]

    public boolean parse() {
        return true;
    }

    public String getURI(){
        return null;
    }
}
