/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertTrue;

public class OntoFoxInputParserTest {

    @Test
    public void testParsingURI() throws IOException {
        OntoFoxInputParser parser = new OntoFoxInputParser();
        parser.parse(getClass().getResource("/ontofoxInputUO.txt").getPath());
        assertTrue("paser.getURI() should not be null", parser.getURI() !=null );
        assertTrue("paser.getURI() has specific value", parser.getURI().equals("http://purl.obolibrary.org/obo/MSI_AO_UO_imports.owl") );
    }

    @Test
    public void testParsingSourceOntology() throws IOException {
        OntoFoxInputParser parser = new OntoFoxInputParser();
        parser.parse(getClass().getResource("/ontofoxInputUO.txt").getPath());
        assertTrue("paser.getSourceOntology() should not be null", parser.getSourceOntology() !=null );
        System.out.println(parser.getSourceOntology());
        assertTrue("paser.getSourceOntolgy() has specific value", parser.getSourceOntology().equals("UO") );
    }

    @Test
    public void testParsingLowerIRIs() throws IOException {
        OntoFoxInputParser parser = new OntoFoxInputParser();
        parser.parse(getClass().getResource("/ontofoxInputUO.txt").getPath());
        assertTrue("paser.getLowerIRIs() should not be null", parser.getLowerIRIs() !=null );
        System.out.println(parser.getLowerIRIs().size());
        assertTrue("paser.getSourceOntolgy() has specific value", parser.getLowerIRIs().size()==18 );
    }
}
